Move design to MVVM
aaru-dps/RedBookPlayer pull request #26
Opened 2021-07-05 19:10 UTC by mnadareski

This PR has the overall goal of moving to an MVVM pattern (fixes #22).

As a part of this, the following changes are implemented:
- Removed all references to Settings object in anything but UI code
- Removed all knowledge of the UI from the view-model and model code
- Added subscriber events for model and view-model code
- Removed UI timer for forcing updates
- Provided more methods to safely set values going down the chain

2021-07-05 19:10 UTC, mnadareski commented
Please note that I am opening this in a draft state because I am not 100% confident that I applied the MVVM pattern to the code correctly.

2021-07-05 23:45 UTC, mnadareski commented
Marking this as ready to review finally, because I feel like I've isolated the pieces properly at this point. All of my local tests are working as expected, with no regressions that I have been able to spot.

2021-07-11 06:04 UTC, mnadareski commented
All future work items have been added as appropriately-tagged issues. Nothing else will be added outside of requested changes.

2021-07-12 16:01 UTC, claunia requested changes

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.Common/Discs/CompactDisc.cs
> +        public void SetLoadDataTracks(bool load) => _loadDataTracks = load;
Use properties.

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.Common/Discs/CompactDisc.cs
> +        public void SetLoadHiddenTracks(bool load) => _loadHiddenTracks = load;
Use properties.

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.Common/Discs/CompactDisc.cs
> +namespace RedBookPlayer.Common.Discs
Is this a view, a model, or a viewmodel?

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.Common/Discs/OpticalDisc.cs
> +    public abstract class OpticalDisc : ReactiveObject
Shouldn't it be called OpticalDiscBase?

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.Common/Discs/OpticalDisc.cs
> +namespace RedBookPlayer.Common.Discs
View, Model or ViewModel?

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.Common/Discs/OpticalDiscFactory.cs
> +namespace RedBookPlayer.Common.Discs
Factories should go in factories namespace and folder imo.

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.Common/PlayerViewModel.cs
> +namespace RedBookPlayer.Common
Namespace, namespace

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.GUI/MainWindow.xaml.cs
>  namespace RedBookPlayer.GUI
namespace namespace. Views views.

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.GUI/PlayerView.xaml.cs
>          public async Task<bool> LoadImage(string path)
This should go in the viewmodel.

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.GUI/PlayerView.xaml.cs
> +            // If the disc isn't initialized, return all '-' characters
This should go in the viewmodel.

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.GUI/PlayerView.xaml.cs
> +        private async Task<string> GetPath()
-> Viewmodel

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.GUI/PlayerView.xaml.cs
> +        private ulong GetCurrentSectorTime()
-> Viewmodel

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.GUI/PlayerView.xaml.cs
> +        private void PlayerViewModelStateChanged(object sender, PropertyChangedEventArgs e)
-> Viewmodel

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.GUI/PlayerView.xaml.cs
> +        public void StopButton_Click(object sender, RoutedEventArgs e) => PlayerViewModel.Stop();
Binding

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.GUI/PlayerView.xaml.cs
> +        public void PlayPauseButton_Click(object sender, RoutedEventArgs e)
Binding

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.GUI/PlayerView.xaml.cs
> +        public void PauseButton_Click(object sender, RoutedEventArgs e) => PlayerViewModel.Pause();
Binding

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.GUI/PlayerView.xaml.cs
> +        public void PlayButton_Click(object sender, RoutedEventArgs e) => PlayerViewModel.Play();
Binding

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.GUI/PlayerView.xaml.cs
> +        public void VolumeUpButton_Click(object sender, RoutedEventArgs e) => PlayerViewModel.SetVolume(PlayerViewModel.Volume + 1);
Binding

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.GUI/PlayerView.xaml.cs
>          public void RewindButton_Click(object sender, RoutedEventArgs e) => PlayerViewModel.Rewind();
Binding

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.GUI/PlayerView.xaml.cs
> +        public void VolumeDownButton_Click(object sender, RoutedEventArgs e) => PlayerViewModel.SetVolume(PlayerViewModel.Volume - 1);
Binding

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.GUI/PlayerView.xaml.cs
> +        public void EnableDeEmphasisButton_Click(object sender, RoutedEventArgs e) => PlayerViewModel.SetDeEmphasis(true);
Binding

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.GUI/PlayerView.xaml.cs
> +        public void DisableDeEmphasisButton_Click(object sender, RoutedEventArgs e) => PlayerViewModel.SetDeEmphasis(false);
Binding

2021-07-12 16:01 UTC, claunia commented on RedBookPlayer.GUI/PlayerView.xaml.cs
> +        public void EnableDisableDeEmphasisButton_Click(object sender, RoutedEventArgs e) => PlayerViewModel.SetDeEmphasis(!PlayerViewModel.ApplyDeEmphasis);
Binding

2021-07-23 23:07 UTC, claunia approved these changes

2021-07-23 23:13 UTC, merged